<?php
// add_action('acf/include_fields', function () {
// 	if (!function_exists('acf_add_local_field_group')) {
// 		return;
// 	}

// 	acf_add_local_field_group(array(
// 		'key' => 'group_662cba05334d2',
// 		'title' => 'Component Hero',
// 		'fields' => array(
// 			array(
// 				'key' => 'field_662cba0515c8e',
// 				'label' => 'Title',
// 				'name' => 'title',
// 				'aria-label' => '',
// 				'type' => 'wysiwyg',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'default_value' => '',
// 				'tabs' => 'visual',
// 				'toolbar' => 'title_bar',
// 				'media_upload' => 0,
// 				'delay' => 0,
// 			),
// 			array(
// 				'key' => 'field_662cbac515c8f',
// 				'label' => 'Content',
// 				'name' => 'content',
// 				'aria-label' => '',
// 				'type' => 'textarea',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'default_value' => '',
// 				'maxlength' => '',
// 				'rows' => '',
// 				'placeholder' => '',
// 				'new_lines' => '',
// 			),
// 			array(
// 				'key' => 'field_66353780e3fe5',
// 				'label' => 'Buttons',
// 				'name' => 'buttons',
// 				'aria-label' => '',
// 				'type' => 'repeater',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'layout' => 'table',
// 				'pagination' => 0,
// 				'min' => 0,
// 				'max' => 0,
// 				'collapsed' => '',
// 				'button_label' => 'Add Row',
// 				'rows_per_page' => 20,
// 				'sub_fields' => array(
// 					array(
// 						'key' => 'field_66353835e3fe8',
// 						'label' => 'Label',
// 						'name' => 'label',
// 						'aria-label' => '',
// 						'type' => 'text',
// 						'instructions' => '',
// 						'required' => 0,
// 						'conditional_logic' => 0,
// 						'wrapper' => array(
// 							'width' => '',
// 							'class' => '',
// 							'id' => '',
// 						),
// 						'default_value' => '',
// 						'maxlength' => '',
// 						'placeholder' => '',
// 						'prepend' => '',
// 						'append' => '',
// 						'parent_repeater' => 'field_66353780e3fe5',
// 					),
// 					array(
// 						'key' => 'field_6635390ee3fec',
// 						'label' => 'Link',
// 						'name' => 'link',
// 						'aria-label' => '',
// 						'type' => 'group',
// 						'instructions' => '',
// 						'required' => 0,
// 						'conditional_logic' => 0,
// 						'wrapper' => array(
// 							'width' => '',
// 							'class' => '',
// 							'id' => '',
// 						),
// 						'layout' => 'block',
// 						'sub_fields' => array(
// 							array(
// 								'key' => 'field_6635385be3fe9',
// 								'label' => 'Type',
// 								'name' => 'type',
// 								'aria-label' => '',
// 								'type' => 'select',
// 								'instructions' => '',
// 								'required' => 0,
// 								'conditional_logic' => 0,
// 								'wrapper' => array(
// 									'width' => '',
// 									'class' => '',
// 									'id' => '',
// 								),
// 								'choices' => array(
// 									'url' => 'url',
// 									'anchor' => 'anchor',
// 								),
// 								'default_value' => 'url',
// 								'return_format' => 'value',
// 								'multiple' => 0,
// 								'allow_null' => 0,
// 								'ui' => 0,
// 								'ajax' => 0,
// 								'placeholder' => '',
// 							),
// 							array(
// 								'key' => 'field_663538bde3fea',
// 								'label' => 'Url',
// 								'name' => 'url',
// 								'aria-label' => '',
// 								'type' => 'url',
// 								'instructions' => '',
// 								'required' => 0,
// 								'conditional_logic' => array(
// 									array(
// 										array(
// 											'field' => 'field_6635385be3fe9',
// 											'operator' => '==',
// 											'value' => 'url',
// 										),
// 									),
// 								),
// 								'wrapper' => array(
// 									'width' => '',
// 									'class' => '',
// 									'id' => '',
// 								),
// 								'default_value' => '',
// 								'placeholder' => '',
// 							),
// 							array(
// 								'key' => 'field_663538e2e3feb',
// 								'label' => 'Anchor',
// 								'name' => 'anchor',
// 								'aria-label' => '',
// 								'type' => 'text',
// 								'instructions' => '',
// 								'required' => 0,
// 								'conditional_logic' => array(
// 									array(
// 										array(
// 											'field' => 'field_6635385be3fe9',
// 											'operator' => '==',
// 											'value' => 'anchor',
// 										),
// 									),
// 								),
// 								'wrapper' => array(
// 									'width' => '',
// 									'class' => '',
// 									'id' => '',
// 								),
// 								'default_value' => '',
// 								'maxlength' => '',
// 								'placeholder' => '',
// 								'prepend' => '',
// 								'append' => '',
// 							),
// 						),
// 						'parent_repeater' => 'field_66353780e3fe5',
// 					),
// 				),
// 			),
// 			array(
// 				'key' => 'field_66354394391b6',
// 				'label' => 'image',
// 				'name' => 'image',
// 				'aria-label' => '',
// 				'type' => 'image',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'return_format' => 'id',
// 				'library' => 'all',
// 				'min_width' => '',
// 				'min_height' => '',
// 				'min_size' => '',
// 				'max_width' => '',
// 				'max_height' => '',
// 				'max_size' => '',
// 				'mime_types' => '',
// 				'preview_size' => 'medium',
// 			),
// 			array(
// 				'key' => 'field_663602bad3514',
// 				'label' => 'url video',
// 				'name' => 'video',
// 				'aria-label' => '',
// 				'type' => 'url',
// 				'instructions' => '',
// 				'required' => 0,
// 				'conditional_logic' => 0,
// 				'wrapper' => array(
// 					'width' => '',
// 					'class' => '',
// 					'id' => '',
// 				),
// 				'default_value' => '',
// 				'placeholder' => '',
// 			),
// 		),
// 		'location' => array(
// 			array(
// 				array(
// 					'param' => 'block',
// 					'operator' => '==',
// 					'value' => 'payfit/hero',
// 				),
// 			),
// 		),
// 		'menu_order' => 0,
// 		'position' => 'normal',
// 		'style' => 'default',
// 		'label_placement' => 'top',
// 		'instruction_placement' => 'label',
// 		'hide_on_screen' => '',
// 		'active' => true,
// 		'description' => '',
// 		'show_in_rest' => 1,
// 	));
// });

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_662cba05334d2',
	'title' => 'Component Hero',
	'fields' => array(
		array(
			'key' => 'field_662cba0515c8e',
			'label' => 'Title',
			'name' => 'title',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'visual',
			'toolbar' => 'title_bar',
			'media_upload' => 0,
			'delay' => 0,
		),
		array(
			'key' => 'field_662cbac515c8f',
			'label' => 'Content',
			'name' => 'content',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_66353780e3fe5',
			'label' => 'Buttons',
			'name' => 'buttons',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_66353835e3fe8',
					'label' => 'Label',
					'name' => 'label',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_66353780e3fe5',
				),
				array(
					'key' => 'field_6635390ee3fec',
					'label' => 'Link',
					'name' => 'link',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6635385be3fe9',
							'label' => 'Type',
							'name' => 'type',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'url' => 'url',
								'anchor' => 'anchor',
							),
							'default_value' => 'url',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_663538bde3fea',
							'label' => 'Url',
							'name' => 'url',
							'aria-label' => '',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_6635385be3fe9',
										'operator' => '==',
										'value' => 'url',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_663538e2e3feb',
							'label' => 'Anchor',
							'name' => 'anchor',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_6635385be3fe9',
										'operator' => '==',
										'value' => 'anchor',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
					'parent_repeater' => 'field_66353780e3fe5',
				),
			),
		),
		array(
			'key' => 'field_66354394391b6',
			'label' => 'image',
			'name' => 'image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_663602bad3514',
			'label' => 'url video',
			'name' => 'video',
			'aria-label' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
		),
		array(
			'key' => 'field_666c6b02fb79b',
			'label' => 'testgroup (copy)',
			'name' => 'testgroup_copy',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_666c6b02fb79c',
					'label' => 'aaaaa',
					'name' => 'aaaaa',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
				array(
					'key' => 'field_666c96a2159d4',
					'label' => 'repeat2',
					'name' => 'repeat2',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_666c96ac159d5',
							'label' => 'group2',
							'name' => 'group2',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_666c96b6159d6',
									'label' => 'text hero',
									'name' => 'text_hero',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
							),
							'parent_repeater' => 'field_666c96a2159d4',
						),
					),
				),
			),
		),
		array(
			'key' => 'field_666c68bb74d66',
			'label' => 'testrepeater',
			'name' => 'testrepeater',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Row',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_666c687e74d64',
					'label' => 'testgroup',
					'name' => 'testgroup',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_666c689174d65',
							'label' => 'aaaaa',
							'name' => 'aaaaa',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
						array(
							'key' => 'field_666c8e0081103',
							'label' => 'bbbb',
							'name' => 'bbbb',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'table',
							'pagination' => 0,
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_666c8e0b81104',
									'label' => 'test',
									'name' => 'test',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_666c8e0081103',
								),
							),
						),
					),
					'parent_repeater' => 'field_666c68bb74d66',
				),
			),
		),
		array(
			'key' => 'field_666ca169c3ae1',
			'label' => 'groupgroup',
			'name' => 'groupgroup',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_666ca17ac3ae2',
					'label' => 'groupAAAA',
					'name' => 'groupaaaa',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_666ca189c3ae3',
							'label' => 'textAAA',
							'name' => 'textaaa',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
						),
					),
				),
				array(
					'key' => 'field_666ca197c3ae4',
					'label' => 'groupCCCC',
					'name' => 'groupcccc',
					'aria-label' => '',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_666ca24f9c620',
							'label' => 'GroupBBBB',
							'name' => 'groupbbbb',
							'aria-label' => '',
							'type' => 'group',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layout' => 'block',
							'sub_fields' => array(
								array(
									'key' => 'field_666ca1a7c3ae5',
									'label' => 'textBBB',
									'name' => 'textbbb',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
								),
							),
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'payfit/hero',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 1,
) );
} );

