FROM docker.io/node:22

WORKDIR /app

COPY package.json .
COPY package-lock.json .
COPY next .

WORKDIR /app/next

RUN npm ci \
  && npx next telemetry --disable \
  && npm run build

EXPOSE 3000

ENV NODE_ENV=production

CMD [ "npm", "start" ]
